### ISSUE TITLE
Undefined method assertions

### ISSUE THREAD

**Issue by shankardevy** [codegram/spinach#169]
Hi
I have the following line in my `features/support/env.rb` to support Minitest framework.

`require 'spinach/frameworks/minitest'`

However, I get `undefined method "assertions"`
which I think is related to this:
https://github.com/seattlerb/minitest/issues/314

I'm using Minitest 5.4.2

**Comment by gtramontina** [comment]
This is caused by https://github.com/seattlerb/minitest/issues/286
The problem seems to be https://github.com/codegram/spinach/blob/master/lib/spinach/frameworks/minitest.rb#L4

I'll submit a PR as soon as I have time to get spinach's codebase running locally… But for the time being, I'm not loading `spinach/frameworks/minitest`; I have a `minitest.rb` in my `features/support/` directory with this:

```ruby
require 'minitest/spec'
MiniTest::Spec.new nil if defined?(MiniTest::Spec)
Spinach.config[:failure_exceptions] << MiniTest::Assertion

class Spinach::FeatureSteps
  attr_accessor :assertions
  include MiniTest::Assertions
  def initialize(*args)
    super *args
    self.assertions = 0
  end
end

```

**Comment by gtramontina** [comment]
👍 better late than ever… 😄
